name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: homework-frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd homework-frontend
          npm install

      - name: Build
        run: |
          cd homework-frontend
          npm run build
        env:
          VITE_API_BASE_URL: https://global-chat-2t51.onrender.com

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: homework-frontend/dist
